### ISSUE TITLE
Gulp-Browserify

### ISSUE THREAD

**Issue by sWimmie** [janpaepke/ScrollMagic#523]
I have setup a workflow with Gulp using an older version of ScrollMagic (1.08.). Now I would like to update this library but when I do insert the latest version (2.0.5.) of jquery.ScrollMagic.min.js I get an error from Gulp-Browserify namely:
{ [Error: module "scrollmagic" not found from "/responsive/components/scripts/fake_316a330b.js"]
plugin: 'gulp-browserify',
showStack: false,
name: 'Error',
message: 'module "scrollmagic" not found from "/responsive/components/scripts/fake_316a330b.js"',
fileName: undefined,
lineNumber: undefined,
stack: 'Error: module "scrollmagic" not found from "/responsive/components/scripts/fake_316a330b.js"\n at notFound (/responsive/node_modules/browserify/index.js:803:15)\n at /responsive/node_modules/browserify/index.js:754:23\n at /responsive/node_modules/browser-resolve/index.js:185:24\n at /responsive/node_modules/browser-resolve/node_modules/resolve/lib/async.js:44:14\n at process (/responsive/node_modules/browser-resolve/node_modules/resolve/lib/async.js:113:43)\n at /responsive/node_modules/browser-resolve/node_modules/resolve/lib/async.js:122:21\n at load (/responsive/node_modules/browser-resolve/node_modules/resolve/lib/async.js:54:43)\n at /responsive/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:22\n at /responsive/node_modules/browser-resolve/node_modules/resolve/lib/async.js:16:47\n at FSReqWrap.oncomplete (fs.js:82:15)' }

When using ScrollMagic.min.js I get the message inside Chrome Uncaught ReferenceError: ScrollMagic is not defined

My setup in my Gulp.js file looks like this:

jsSources = [
  'components/scripts/jqloader.js',
  'components/scripts/TweenMax.min.js',
  'components/scripts/ScrollMagic.min.js',
  'components/scripts/jquery.scrollmagic.min.js',
  'components/scripts/script.js'
];

gulp.task('js', function() {
  gulp.src(jsSources)
    .pipe(concat('script.js'))
    .pipe(browserify())
    .on('error', gutil.log)
    .pipe(gulpif(env === 'production', uglify()))
    .pipe(gulp.dest(outputDir + 'js'))
    .pipe(connect.reload())
});

What am I doing wrong here?

**Comment by janpaepke** [comment]
About ten years late -- sorry about that.

The "module scrollmagic not found" error with gulp-browserify was a module resolution issue. v2's package.json used a non-standard `main` field structure, and browserify needed specific configuration to resolve ScrollMagic's module path. The typical fix was to add a `paths` option to browserify pointing to `node_modules/scrollmagic/scrollmagic/uncompressed/` or to use the `browser` field.

v3 is a proper ES module with a standard `main`/`module`/`exports` configuration in package.json. It works out of the box with any modern bundler (Rollup, Webpack, Vite, esbuild) and also ships a UMD build. No special configuration needed -- just `import ScrollMagic from 'scrollmagic'`.

---
**ScrollMagic v3 is now available** — a complete rewrite with an entirely new architecture and API. v2 will not receive further updates (2.0.9 is the final release).

👉 `npm install scrollmagic@next` — [Docs](https://github.com/janpaepke/ScrollMagic/blob/main/README.md) · [Release notes](https://github.com/janpaepke/ScrollMagic/releases/tag/v3.0.0-beta.0) · [npm](https://www.npmjs.com/package/scrollmagic/v/3.0.0-beta.0)
